### ISSUE TITLE
IndexError when read_material_file with no line startswith 'Ns'

### ISSUE THREAD

**Issue by fuyb1992** [angeloskath/simple-3dviz#8]
IndexError triggered when call `read_material_file ` function to read a model.mtl file with no line startswith 'Ns'.
Errors:
```
File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/atiss/lib/python3.8/site-packages/simple_3dviz/io/__init__.py", line 27, in read_material_file
    return {
  File "/usr/local/anaconda3/envs/atiss/lib/python3.8/site-packages/simple_3dviz/io/material.py", line 25, in __init__
    self.read(filename)
  File "/usr/local/anaconda3/envs/atiss/lib/python3.8/site-packages/simple_3dviz/io/material.py", line 113, in read
    self._Ns = float([
IndexError: list index out of range
```

**Comment by JackW987** [comment]
> IndexError triggered when call `read_material_file ` function to read a model.mtl file with no line startswith 'Ns'. Errors:
> 
> ```
> File "<stdin>", line 1, in <module>
>   File "/usr/local/anaconda3/envs/atiss/lib/python3.8/site-packages/simple_3dviz/io/__init__.py", line 27, in read_material_file
>     return {
>   File "/usr/local/anaconda3/envs/atiss/lib/python3.8/site-packages/simple_3dviz/io/material.py", line 25, in __init__
>     self.read(filename)
>   File "/usr/local/anaconda3/envs/atiss/lib/python3.8/site-packages/simple_3dviz/io/material.py", line 113, in read
>     self._Ns = float([
> IndexError: list index out of range
> ```

I get the same problem with 3DFront dataset,I find the 3DFront model.mtl don't have the Ns value

**Comment by paschalidoud** [comment]
Hi @JackW987 and @fuyb1992,

I committed a modification in the code a couple of days ago that sets Ns=10 in case no Ns is provided in the material file. With this modification, the above issue should be fixed. We still haven't updated the pip but if you install simple-3dviz from the github it should work.

We will try to also update the pip later today.

Best,
Despoina

**Comment by fuyb1992** [comment]
Thanks @paschalidoud

**Comment by JackW987** [comment]
> Hi @JackW987 and @fuyb1992,
> 
> I committed a modification in the code a couple of days ago that sets Ns=10 in case no Ns is provided in the material file. With this modification, the above issue should be fixed. We still haven't updated the pip but if you install simple-3dviz from the github it should work.
> 
> We will try to also update the pip later today.
> 
> Best, Despoina

Thanks for your reply!

**Comment by YosinLiu** [comment]
When I set Ns=10 like this:
 try:
                self._Ns = float([
                    float(l.strip().split()[1:][0])
                    for l in lines if l.strip().startswith("Ns")
                ][0])
            except (IndexError, ValueError) as e:
                 # IndexError 可能会在尝试访问列表第一个元素时抛出，如果列表为空
                 # ValueError 可能会在 float() 转换失败时抛出
                self._Ns = 10
I encouter the problem like this. What  can  I do next ?
Traceback (most recent call last):
  File "preprocess_data.py", line 357, in <module>
    main(sys.argv[1:])
  File "preprocess_data.py", line 346, in main
    render(
  File "/root/DiffuScene/DiffuScene/scripts/utils.py", line 235, in render
    scene.add(r)
  File "/root/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/scenes.py", line 60, in add
    renderable.init(self._ctx)
  File "/root/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/renderables/textured_mesh.py", line 197, in init
    self.material = self._material
  File "/root/anaconda3/envs/diffuscene/lib/python3.8/site-packages/simple_3dviz/renderables/textured_mesh.py", line 229, in material
    self._prog["ambient"].write(self._material.ambient.tobytes())
  File "/root/anaconda3/envs/diffuscene/lib/python3.8/site-packages/_moderngl.py", line 95, in write
    self.ctx._write_uniform(
_moderngl.Error: invalid uniform size
